services:
    backend:
        build: .
        image: mhz19-next
        env_file: .env
        network_mode: host
        # ports:
        #     - 8888:8888
        #     - 5353:5353/tcp
        #     - 5353:5353/udp
        volumes:
            - ./database.bin:/app/database.bin
