export const SET_BOOTSTRAP_DATA = 'SET_BOOTSTRAP_DATA';
export const ADD_MHZ_DOC = 'ADD_MHZ_DOC';
export const SET_HISTORY_OPTION = 'SET_HISTORY_OPTION';
export const SAVE_ZIGBEE_DEVICE_MESSAGE = 'SAVE_ZIGBEE_DEVICE_MESSAGE';
export const GET_MHZ_DOCS_PENDING = 'GET_MHZ_DOCS_PENDING';
export const GET_MHZ_DOCS_SUCCEED = 'GET_MHZ_DOCS_SUCCEED';
export const GET_MHZ_DOCS_FAILED = 'GET_MHZ_DOCS_FAILED';
